### ISSUE TITLE
Huge delays with LibreOffice

### ISSUE THREAD

**Issue by lances101** [Wox-launcher/Wox.Plugin.ClipboardManager#3]
It seems that if you launch any LibreOffice product after this plugin is initialized, pasting will be delayed for a couple of seconds. 

[This issue was discussed in the main Wox repo](https://github.com/qianlifeng/Wox/issues/342)

**Comment by georgeto** [comment]
Libre/OpenOffice seem to have a fundamental problem with clipboard viewers.
https://bz.apache.org/ooo/show_bug.cgi?id=49907
https://forum.openoffice.org/en/forum/viewtopic.php?f=7&t=69001#p307743

**Comment by lances101** [comment]
Closing this issue for the same reasons that https://github.com/Wox-launcher/Wox/issues/342 (not caused by Wox)
