### ISSUE TITLE
Is there any way to clear clipboard history?

### ISSUE THREAD

**Issue by olbb** [Wox-launcher/Wox.Plugin.ClipboardManager#5]
Hello,
Is there any way to clear clipboard history?
Thank you.

**Comment by katsusuke** [comment]
Try to kill wox.exe and delete PATH_TO_WOX\Config\ImageCache.dat .

**Comment by standin000** [comment]
can not find ImageCache.dat with wox 1.3.524, it seems exit wox will clear cliboard history.
